image: python:3.7.4
stages:
  - ver
  - init
  - staging
  - production
ver:
  stage: ver
  script:
    - python --version
    - whoami
init:
  stage: init
  script:
    - apt-get update -qy
    - apt-get install -y postgresql-server-dev-all
    - pip install -r requirements.txt
deploy_staging:
  stage: staging
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=dooa-2257-staging --api-key=$HEROKU_API_KEY
deploy_production:
  stage: production
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=dooa-2257-production --api-key=$HEROKU_API_KEY
  only:
    - master
  